server:
  port: 7070

eureka:
  client:
    registerWithEureka: true
     # 设置是否从注册中心获取注册信息（缺省true）
     # 因为这是一个单点的EurekaServer，不需要同步其它EurekaServer节点的数据，故设为false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:7070/eureka/
  instance:
      prefer-ip-address: true
#      //租期更新时间间隔（默认30秒）  //租期到期时间（默认90秒）
#      leaseRenewalIntervalInSeconds: 30
#      leaseExpirationDurationInSeconds: 90


  server:
    waitTimeInMsWhenSyncEmpty: 4000
    # //（设为false，关闭自我保护主要）  //清理间隔（单位毫秒，默认是60*1000）  更改Eureka更新频率将打破服务器的自我保护功能
#    enableSelfPreservation: false
    evictionIntervalTimerInMs: 300000

spring:
  application:
    name: grayscale-eureka


management:
  security:
    enabled: false